### ISSUE TITLE
Bug: type mismatch for complex compounds having nullable and non-nullable types

### ISSUE THREAD

**Issue by antailyaqwer** [tamimattafi/kabin#11]
# Problem
If we will have complex compounds hierarchy, and in one place compound is considered nullable, an in another - not null, nullable query is used, and compiler throws "type mismatch" error.

Environment: kabin: 0.1.0-alpha05; android target.
SQLite version (according to [documentation](https://developer.android.com/reference/android/database/sqlite/package-summary.html)): 3.39 (API 34).

# Example
```kotlin
data class ACompound(
    @Embedded
    val entity: AEntity,

    @Relation(
        entity = BEntity::class,
        parentColumn = "bId",
        entityColumn = "id"
    )
    // query1 returning nullable compound is generated
    val bCompound: bCompound?,
    
        @Relation(
        entity = CEntity::class,
        parentColumn = "cId",
        entityColumn = "id"
    )
    val cCompound: cCompound,
)

data class CCompound(
    @Embedded
    val entity: CEntity,

    @Relation(
        entity = BEntity::class,
        parentColumn = "bId",
        entityColumn = "id"
    )
    // query1 will be still used in dao, though we have non-nullable returning type
    val bCompound: bCompound,
```

Maybe we should add postfix "Optional" or "Nullable" to queries returning nullable type to avoid such problems.

**Comment by tamimattafi** [comment]
A prefix such as `Optional` should be used for queries that return `Nullable` values, because the signature of `Nullable` and `NotNullable` return types are the same for JVM and other runtimes.
